language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django>=1.10,<1.11"
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.1"
matrix:
  exclude:
    - python: 3.5
      env: DJANGO="django>=1.7,<1.8"
  exclude:
    - python: 2.7
      env: DJANGO="django>=2.0,<2.1"
install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - python setup.py -q install
script: python runtests.py
notifications:
  email: false
