language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django>=1.9,<1.10"
  - DJANGO="django>=1.10,<1.11"
  - DJANGO="django>=1.11,<1.12"
matrix:
  exclude:
    - python: 3.5
      env: DJANGO="django>=1.7,<1.8"
install:
  - pip install $DJANGO
  - pip install "PyOpenSSL>=0.15,<0.16"
  - pip install requests
  - python setup.py -q install
script: python runtests.py
notifications:
  email: false
